Integrate optional plotting capabilities into ashist()
xgi-org/xgi pull request #636
Opened 2024-12-08 20:17 UTC by willcollins10

### Description

This PR integrates optional plotting capabilities directly into the `ashist()` function. Users can now generate plots (`'bar'`, `'line'`, or `'step'`) by setting the `plot` parameter to `True` and customize plot appearance using `plot_kwargs`.

### Changes Made

- Added `plot` and `plot_kwargs` parameters to the `ashist()` function.
- Implemented plotting logic using `matplotlib.pyplot` based on the specified plot type.
- Automatically sets axis labels and plot titles using metadata attributes.
- Adds vertical lines for bin edges if `bin_edges` is `True`.

### Testing

- Added unit tests to validate different plot types and `plot_kwargs`.
- Ensured that invalid plot types raise appropriate errors.
- Verified interaction with existing parameters like `density` and `bin_edges`.

### Related Issues

Closes #<606>

2024-12-09 16:32 UTC, nwlandry commented
@willcollins10 --- thanks for the PR! I will try to take a look this afternoon!

2024-12-09 16:42 UTC, nwlandry commented
@willcollins10 --- side note, the tests fail because the example you added in the docstring never defines `H`.

2024-12-10 15:42 UTC, nwlandry requested changes
Overall looks awesome! Three main comments: (1) move the plotting contents to a helper function and (2) add the ability to plot a scatterplot, and (3) fix the docstring so that the doctests pass. Thanks for the contribution!

2024-12-10 15:42 UTC, nwlandry commented on xgi/stats/__init__.py
> +                import matplotlib.pyplot as plt
If users have installed xgi, I believe that they will also have matplotlib by default, so not sure that you need to check this.

2024-12-10 15:42 UTC, nwlandry commented on xgi/stats/__init__.py
> +        if plot:
Can you break this out into a modular helper function with an underscore prefix like `_plot_hist` or similar?

2024-12-10 15:42 UTC, nwlandry commented on xgi/stats/__init__.py
> +        >>> H.nodes.degree.ashist(plot='bar', plot_kwargs={'color': 'red'})
Define what `H` is. maybe a small example? like
```python
H = xgi.Hypergraph([[1, 2, 3], [3, 4], [1, 3, 6]])
H.nodes.degree.ashist(plot='bar', plot_kwargs={'color': 'red'})
```

2024-12-10 15:42 UTC, nwlandry commented on xgi/stats/__init__.py
> +            if plot_type == "bar":
can you add a "scatter" option or replace the "line" option with a scatterplot only plotting the points?

2024-12-10 15:42 UTC, nwlandry commented on xgi/stats/__init__.py
> +                    ax.axvline(row["bin_lo"], color="gray", linestyle="--", alpha=0.5)
If `bin_edges` is false in the function argument, how do you access it here?

2024-12-10 15:42 UTC, nwlandry commented on xgi/stats/__init__.py
> +                    ax.axvline(row["bin_lo"], color="gray", linestyle="--", alpha=0.5)
Disregard this. I was just confused what bin_edges did.

2026-06-01 12:59 UTC, maximelucas commented
@nwlandry I think I addressed your comments, if you're happy we can close.

2026-07-06 16:22 UTC, maximelucas commented
Quick ping @nwlandry :)

2026-07-09 18:11 UTC, nwlandry approved these changes
Looks good, @maximelucas! Thanks for the ping :)

2026-07-10 03:54 UTC, merged